version: '3.8'

services:
  api:
    build:
      context: ./CRM.API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env # Load root .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./CRM.API/logs:/app/logs

  client:
    build:
      context: ./crm.Client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    env_file:
      - .env # Load root .env
